README.md

Nit - fix link in Readme. 
I tested it locally in VSCode, link now works.

[Mike] Fix link

---

transition_guides_for_deprecated_API_endpoints/classification_functionality_example.py

Minor edit to clarify content in the code base
Edit in-line comment - no tests required

Nit: Change text in CLF cookbook

---

README.md

Updates the README to mention the latest GPT-3 model, `text-davinci-003`.

Update README for text-davinci-003

---

transition_guides_for_deprecated_API_endpoints/search_functionality_example.py

Fixing typo in parameters usage

---

examples/azure/finetuning.ipynb

Fixing issue encountered when using this in some contexts (like virtual environments in notebooks). @sorinsuciu-msft FYI

Added .default scope to URI to get token using DefaultAzureCredential

---

examples/How_to_handle_rate_limits.ipynb

Route rate limit increase requests to form instead of our support email

Update notebook to point to form

---

examples/azure/completions.ipynb
examples/azure/embeddings.ipynb
examples/azure/finetuning.ipynb

* Updated `api_version`s to `2022-12-01` (GA)
* Added completions notebook
* Adjusted fine-tuning and embedding example

Azure OpenAI GA

---

examples/fine-tuned_qa/olympics-2-create-qa.ipynb

davinci-instruct-beta-v2 model doesn't exist anymore. It has been replaced by davinci-instruct-beta-v3

Replaced non-existent model with the new version.

---

examples/Question_answering_using_embeddings.ipynb

`SEPARATOR` is being used to construct a prompt for use with the completions endpoint

Encode separator for completions endpoint

---

examples/Clustering.ipynb

Updated the penultimate markdown to align with the code in the following cell

Updated a markdown in Clustering.ipynb

---

solutions/web_crawl_Q&A/web-qa.py

This pull request fixes the UnicodeEncodeError in the code by adding encoding="utf-8" to the open() function calls.

Fix UnicodeEncodeError

---

examples/vector_databases/pinecone/Gen_QA.ipynb

Added an example for using Pinecone vector DB with Open AI embedding and completion endpoints for retrieval-augmented generative QA

added pinecone-openai gen qa example

---

examples/vector_databases/Using_vector_databases_for_embeddings_search.ipynb

Fixed commented out vector

---

apps/file-q-and-a/README.md

Line 14 -> I think it should be "call made to the endpoint" instead of "call made the the endpoint"

Changed "the the endpoint" to "to the endpoint"

---

examples/vector_databases/pinecone/Gen_QA.ipynb

fix typo in Gen_QA.ipynb

---

examples/azure/completions.ipynb
examples/azure/finetuning.ipynb

Tidy two of the Azure example notebooks.

Cleaning Azure notebook examples

---

examples/vector_databases/Using_vector_databases_for_embeddings_search.ipynb

The suffix at the end of the cluster name is a new addition that the WCS now mandates when creating sandboxes.

Weaviate: update links, minor corrections

---

examples/fine-tuned_qa/olympics-3-train-qa.ipynb

we check that he separator > we check that the separator
; )

Fix minor spelling issue

---

examples/fine-tuned_qa/olympics-3-train-qa.ipynb

the examples from the traing set -> the examples from the training set

Fix minor spelling issue in examples/fine-tuned_qa/olympics-3-train-qa.ipynb

---

examples/Question_answering_using_embeddings.ipynb
text_comparison_examples.md

I added Qdrant as another example whenever any vector database is mentioned.

List Qdrant among the other vector databases

---

examples/Embedding_long_inputs.ipynb

programatically -> programmatically

Fix typo in Embedding_long_inputs.ipynb

---

README.md
examples/azure/chat.ipynb
examples/azure/finetuning.ipynb

Chat completions on Azure have been released to the public under the preview version '2023-03-15-preview': [Reference](https://techcommunity.microsoft.com/t5/ai-cognitive-services-blog/working-with-gpt-4-and-chatgpt-models-on-azure-preview/ba-p/3773595)
GitHub preview of the notebook: https://github.com/cmurtz-msft/openai-cookbook/blob/azure-chat/examples/azure/chat.ipynb

[Azure] Chat completions example

---

examples/vector_databases/Using_vector_databases_for_embeddings_search.ipynb
examples/vector_databases/typesense/.gitignore
examples/vector_databases/typesense/docker-compose.yml

👋 Following up from my email conversation with @logankilpatrick, I've added an example of how to use [Typesense](https://typesense.org) as a vector datastore and implement similarity search.

Add Typesense example to vector databases

---

examples/vector_databases/analyticdb/Getting_started_with_AnalyticDB_and_OpenAI.ipynb

Hi there,
I'm excited to open this PR to add an example of support for using a fully Postgres syntax compatible database 'AnalyticDB' as a datastore. AnalyticDB is a distributed Cloud-Native vector database. It works better when data comes to large scale. 
It also support absolute out-of-box experience allow to scale into billions of data vectors processing with rich features including indexing algorithms, structured & non-structured data features, realtime update, distance metrics, scalar filtering, time travel searches etc.  It is a good choice for vector storage.

Add getting started with AnalyticDB distributed vector database example

---

README.md
apps/chatbot-kickstarter/requirements.txt

Added tiktoken to requirements file and updated README to include chatbot-kickstarter

Chatbot Kickstarter readme and requirements updates

---

examples/vector_databases/pinecone/Gen_QA.ipynb
examples/vector_databases/qdrant/QA_with_Langchain_Qdrant_and_OpenAI.ipynb
examples/vector_databases/redis/getting-started-with-redis-and-openai.ipynb

1. modify commands like docker compose -> docker-compose
2. spell like 'Hash' -> 'HASH'
3. spelling in markdown

fix: about spelling and command

---

examples/vector_databases/typesense/README.md

@logankilpatrick Following up from our conversation, I've opened this PR to add a README for Typesense.

Add README for Typesense

---

examples/api_request_parallel_processor.py

fixed bug for non-serializable Error

Fix bugs at api_request_parallel_processor.py

---

examples/vector_databases/Using_vector_databases_for_embeddings_search.ipynb

chore: fixed broken URL in markdown

---

examples/vector_databases/weaviate/getting-started-with-weaviate-and-openai.ipynb
examples/vector_databases/weaviate/hybrid-search-with-weaviate-and-openai.ipynb
examples/vector_databases/weaviate/question-answering-with-weaviate-and-openai.ipynb

1. getting-started-with-weaviate-and-openai.ipynb
2. hybrid-search-with-weaviate-and-openai.ipynb
3. question-answering-with-weaviate-and-openai.ipynb

fix: some typo and add execution command sample

---

examples/How_to_build_a_tool-using_agent_with_Langchain.ipynb

1. add link for creating Pinecone API key
2. add environment variable to pinecone init
3. add missing pip install for openai and wget

[Pinecone]: Add link for creating Pinecone API key and environment variable to pinecone init

---

examples/vector_databases/redis/README.md

Corrected the Redis client list supporting Vector Search.  @tylerhutcherson

Fix Redis supported client list

---

.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/get-help.md
.github/ISSUE_TEMPLATE/problem-report.md

Update issue templates

---

examples/vector_databases/qdrant/QA_with_Langchain_Qdrant_and_OpenAI.ipynb

docs: fix typo in QA_with_Langchain_Qdrant_and_OpenAI.ipynb

---

apps/chatbot-kickstarter/chat.py

Update `chat.py` removing an unnecessary string.

Update `chat.py` removing an unnecessary string

---

examples/vector_databases/pinecone/GPT4_Retrieval_Augmentation.ipynb

Fix to issue #418 — adds a missing data formatting loop that creates `data`

added data creation loop

---

README.md

It would be awesome if [LMQL](https://lmql.ai) was included in the list of prompting libraries and tools.
LMQL is an open source programming language for large language models. It supports typed prompting with control flow, constraints, and tools. 
We started working on LMQL in June 2022 and also wrote a paper about it
*Prompting Is Programming: A Query Language for Large Language Models*, https://arxiv.org/abs/2212.06094, which was accepted to PLDI'23. 
I respect the choice of papers that you highlight in the README, so I limited this PR to the inclusion of our project page for now.

Add LMQL to README

---

examples/How_to_call_functions_with_chat_models.ipynb

The correct value is `function_call`.

Fix `finish_reason` in function calling cookbook

---

examples/How_to_call_functions_with_chat_models.ipynb

Fix function description, hopefully make it more clear for readers and model.

Fix ask_database in call functions with chat model example

---

apps/chatbot-kickstarter/README.md

I just fixed duplicate "basic".
https://github.com/openai/openai-cookbook/blob/41a5d394ca355e276ba21290696116c33f55ad9f/apps/chatbot-kickstarter/README.md?plain=1#L3

Fix typo in README.md

---

examples/data/styles_2k.csv
examples/vector_databases/redis/README.md
examples/vector_databases/redis/redis-hybrid-query-examples.ipynb

This notebook has examples of running hybrid VSS queries in Redis on openai generated embeddings with ecommerce dataset

Add notebook with Redis hybrid VSS queries examples

---

apps/file-q-and-a/nextjs/src/services/getEmbeddingsForText.ts

Fix typo in getEmbeddingsForText.ts

---

examples/Question_answering_using_a_search_API.ipynb

"This answer which will be used to..." --> "This answer will be used to..."

Fix typo in Question_answering_using_a_search_API.ipynb

---

examples/How_to_call_functions_for_knowledge_retrieval.ipynb

Hi,
I've created this pull request to add a simple script that checks whether the data/papers directory exists or not. This addition is particularly useful when running the project on platforms like Google Colab, where the directory structure might not be pre-configured.

create/check data dir for arxiv's papers

---

examples/How_to_handle_rate_limits.ipynb

Replace deprecated model "code-cushman-001" with "gpt-3.5-turbo".

Replace deprecated model in How_to_handle_rate_limits.ipynb

---

examples/vector_databases/analyticdb/QA_with_Langchain_AnalyticDB_and_OpenAI.ipynb

Fix typo in QA_with_Langchain_AnalyticDB_and_OpenAI.ipynb

---

examples/evaluation/How_to_eval_abstractive_summarization.ipynb

small typo on publication date

fix date typo

---

examples/vector_databases/redis/redis-hybrid-query-examples.ipynb

Fix typo in redis-hybrid-query-examples.ipynb

---

examples/How_to_finetune_chat_models.ipynb

builds off the last fine-tuning example, but simplifying things and using the latest python package

add new fine-tuning example

---

.gitignore
examples/How_to_finetune_chat_models.ipynb

cleans up the notebook and runs it from scratch. minor language tweaks here and there.

small improvements to fine-tuning cookbook

---

examples/How_to_finetune_chat_models.ipynb

displays data, improves writing here and there

more fine-tuning improvements

---

examples/How_to_finetune_chat_models.ipynb

fixes the levels in the titles

update titles in fine-tuning cookbook

---

text_comparison_examples.md

My PR updates the file with improved language and clarity. I've also made some minor changes to improve readability.

[revise] made small edits and fixed typos

---

README.md

Sematic Kernel has supported Java.

[Updage] update README.md with Java support of Sematic Kernel

---

examples/evaluation/How_to_eval_abstractive_summarization.ipynb

Yes I see the irony in my commit message 😄

small typo fix

---

examples/azure/chat_with_your_own_data.ipynb

Adds a notebook showing how to access the Azure chat completion models with your own data (preview) with the Python SDK.

[azure] bring your own data example

---

.github/workflows/stale.yml

automatically close stale pull requests

configure stale workflow

---

examples/Code_search.ipynb
examples/Get_embeddings.ipynb

- Code_search.ipynb: [Improve comments and add explanations](https://github.com/openai/openai-cookbook/commit/387161d099c441da11e2844c9297e66cd1141729)
- Get_embeddings.ipynb: [Improve descriptions and add negative examples](https://github.com/openai/openai-cookbook/commit/7dfe57664e1d63580914ebb34deae2d40b5a135b)

Improve code_search and get_embedding notebooks.

---

examples/vector_databases/cassandra_astradb/Philosophical_Quotes_CQL.ipynb

This is very minor, just aesthetic fixes. Thank you!

Fix spelling error + misplaced copypaste in the CQL notebook

---

examples/api_request_parallel_processor.py

Small improvements to parallel processing script.
- The same `session` is new reused across http calls
- Formatted the file with `black`
Makes the script more performant

Improve parallel processing script

---

README.md

[readme] include link to related resources

---

examples/vector_databases/README.md

Add Mongodb Atlas Vector Search For Vector Databases
List the major and minor changes.
- Major Changes
- ...
- Minor Changes
- ...
- Sections have informative titles.
- Key takeaways are upfront.
- Short paragraphs and topic sentences are used.
- Sentences are simple and unambiguous.
- Demonstrative pronouns are avoided or clearly referenced.
- No left-branching sentences.
- Terminology is specific and avoids jargon.
- Provides solutions to common problems.
- Code examples are general and exportable.
- Styling and formatting align with existing documentation.
- Consistent use of punctuation and case.
**Note:** For additional guidelines on writing good documentation, check out [What Makes Documentation …

Add Mongodb Atlas Vector Search

---

examples/third_party_examples/financial_document_analysis_with_llamaindex.ipynb

Adds a missing period.
Grammar.

fix minor typo in financial_document_analysis_with_llamaindex

---

README.md
related_resources.md

Hello!
[Haystack](https://github.com/deepset-ai/haystack) is a popular Python LLM orchestration framework.
It supports OpenAI models for text generation and embeddings.
It would be nice to add it to the "Prompting libraries & tools" section...

Add Haystack to Prompting libraries & tools

---

related_resources.md

Sort tools and libraries list alphabetically
Choosing an impartial sorting order

sort tools and libraries list alphabetically

---

examples/How_to_count_tokens_with_tiktoken.ipynb

We were getting an error because were using the model name instead of the tokenizer name here. This fixes it.

[tiktoken_counting] fix tokenizer name

---

examples/Backtranslation_of_SQL_queries.py

Fix typo in Backtranslation_of_SQL_queries.py

---

examples/How_to_stream_completions.ipynb

Small typo fix - capital letter.

Fix typo in How_to_stream_completions.ipynb

---

examples/vector_databases/neon/README.md

Minor edits to the Neon README file.
- Fix extension name typo
- Fix minor typo
- [yes ] Is the writing easily skimmable?
- Sections have informative titles.
- Key takeaways are upfront.
- Short paragraphs and topic sentences are used.
- [yes] Is the writing quality high?
- Sentences are simple and unambiguous.
- Demonstrative pronouns are avoided or clearly referenced.
- No left-branching sentences.
- [yes] Is the content universally helpful?
- Terminology is specific and avoids jargon.
- Provides solutions to common problems.
- Code examples are general and exportable.
- [ yes] Is the content consistent?
- Styling and formatting align with existing documentation.
- Consistent use of punctuation and case.

Update Neon cookbook README.md

---

examples/vector_databases/README.md

Add Neon Postgres to the list of vector databases. Neon's notebook is included in this repository under the neon directory.
Added a link to Neon Postgres to the list of vector databases.
Provides a link to Neon, which now has a notebook in the this repository, under the neon directory.
- [yes ] Is the writing easily skimmable?
- Sections have informative titles.
- Key takeaways are upfront.
- Short paragraphs and topic sentences are used.
- [yes ] Is the writing quality high?
- Sentences are simple and unambiguous.
- Demonstrative pronouns are avoided or clearly referenced.
- No left-branching sentences.
- [yes ] Is the content universally helpful?
- Terminology is specific and avoids jargon.
- Provides solutions to common problems.
- Code examples are general and exportable.
- [ yes] Is …

Add Neon Postgres to the list of vector databases in the README

---

.github/pull_request_template.md
README.md
registry.yaml
registry_schema.json

Adds the registry file that indicates which content should be rendered on cookbook.openai.com

Add registry

---

related_resources.md

Adding litellm to relevant resources

Adding litellm to relevant resources

---

registry.yaml

Update registry.yaml to add Weights & Biases examples for the cookbook website.
Update registry.yaml
- Major Changes
- Update registry.yaml to add Weights & Biases examples
Discoverability on the more popularly rendered website
- Sections have informative titles.
- Key takeaways are upfront.
- Short paragraphs and topic sentences are used.
- Sentences are simple and unambiguous.
- Demonstrative pronouns are avoided or clearly referenced.
- No left-branching sentences.
- Terminology is specific and avoids jargon.
- Provides solutions to common problems.
- Code examples are general and exportable.
- Styling and formatting align with existing documentation.
- Consistent use of punctuation and case.
When contributing a new example, make sure to add a new entry for it in …

Update registry.yaml to add Weights & Biases examples

---

examples/third_party_examples/GPT_finetuning_with_wandb.ipynb
examples/third_party_examples/Openai_monitoring_with_wandb_weave.ipynb

The website generation doesn't play nicely with notebookso that don't have the title as the first element.

Fix titles for wandb notebooks

---

.github/pull_request_template.md
README.md

Updates the README and PR template

Update contributions process

---

examples/book_translation/translate_latex_book.ipynb

fix typo in examples/book_translation/translate_latex_book.ipynb

---

articles/related_resources.md

Adding Portkey.ai to list of tools

Add Portkey to related resources

---

registry.yaml

Update deterministic outputs title

---

examples/GPT_with_vision_for_video_understanding.ipynb

Fix small typo
Word misspelled

docs: fix typo

---

examples/Whisper_processing_guide.ipynb

Uses new spec and cleans up notebook a bit.

SDK fixes and slight clean up to Whisper pre/post processing recipe

---

examples/Assistants_API_overview_python.ipynb

Added a couple more links to resources for sections in the Assistants API Overview cookbook. Also re-ran since they Retrieval had failed in the uploaded version.

Assistants API Overview: More Bug Fixes

---

examples/How_to_call_functions_with_chat_models.ipynb

The goal of this PR is to do the following:
- Update this cookbook with the newest schema changes that utilizes 'tools' and 'tool_call' instead of the deprecated 'function' and 'function_call'
- Add a section on parallel function calling
These changes capture some of our most recent features from Dev Day
---
We will rate each of these areas on a scale from 1 to 4, and will only accept contributions that score 3 or higher on all areas. Refer to our [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUT …

Add parallel function calling

---

articles/related_resources.md

This PR adds embedchain. Embedchain is an open-source Python library to load, index, retrieve and sync data with LLMs.
This improves the related resources list and makes it comprehensive.
---

Add embedchain to articles/related_resources

---

examples/fine-tuned_qa/olympics-3-train-qa.ipynb

docs: fix typo in olympics-3-train-qa.ipynb

---

examples/How_to_build_an_agent_with_the_node_sdk.mdx

Because `messages` are already an array, push should be an object, not an array.

docs: Fix the code error at "Creating the agent function"

---

examples/How_to_build_an_agent_with_the_node_sdk.mdx

Update the node example as "function_call" is deprecated.
"function_call" is deprecated.
---

Update the node example as "function_call" is deprecated.

---

articles/related_resources.md

Added a link to my popular prompt engineering guides and my LinkedIn video course, which has had 100k learners so far
These resources are complementary to some of the ones included in the cookbook and are also already pretty ppular
---

Added a guide and a course

---

examples/Get_embeddings_from_dataset.ipynb

Fixed an keyword argument for `get_embeddings` function
Bugfix

Update Get_embeddings_from_dataset.ipynb from engine to model as function argument to get_embeddings

---

articles/how_to_work_with_large_language_models.md

Added a new example of how to control a large language model (playing out a scenario) and updated the **Code Capabilities** section as the `codex` models are deprecated, GPT-4 is the [reccomended replacement](https://platform.openai.com/docs/deprecations/2023-03-20-codex-models)
Codex models are still often mentioned throughout the cookbook despite being shut down back in March of 2023 - The Researcher Access Program no longer seems to provide access to the codex models, so they should not be included in any documentation.

Updated how_to_work_with_large_language_models.md to keep the information up-to-date

---

examples/Using_logprobs.ipynb
registry.yaml

Creating a 'using logprobs' notebook that shows how to use logprobs for classification, evaluation of rag Q&A, and a simple autocompletion system.
Logprobs were a huge dev. ask, and this cookbook was directly requested to show users a few use cases for logprobs.
---

Cookbook around using logprobs

---

examples/How_to_build_a_tool-using_agent_with_Langchain.ipynb

Fixes the link to langchain agents page

fix: URL to langchain agents page

---

articles/related_resources.md

Added a one-line description on HoneyHive in the related resources section.
The change gives better visibility to tools developers can use to improve their iteration velocity with OpenAI.
---

Added HoneyHive to related resources

---

examples/Using_logprobs.ipynb

updates to coloring, and intro paragraph

---

examples/How_to_call_functions_for_knowledge_retrieval.ipynb
examples/How_to_call_functions_with_chat_models.ipynb

Changed the cookbook to use the Python SDK instead of the requests library.
The page of the cookbook was outdated and had to reflect the newest capabilities.
---

Update function calling examples to Python SDK

---

examples/vector_databases/qdrant/Using_Qdrant_for_embeddings_search.ipynb

Qdrant will spend about 8GB of memory if you upload this dataset.
For the docker default setting, the container will die without information.
---

docs: add tip

---

examples/How_to_handle_rate_limits.ipynb

Resolve the issues #1038 
This changes are necessary's in order to show the file in its correct format.
---

Fix rate limit increase link in How_to_handle_rate_limits.ipynb

---

examples/Fine_tuning_for_function_calling.ipynb

Fix typo in Fine_tuning_for_function_calling.ipynb

---

examples/How_to_combine_GPT4v_with_RAG_Outfit_Assistant.ipynb
registry.yaml

Change the "gptv" to "gpt-4v"
Change the name of the model to match language.

Update gptv terminology to gpt-4v

---

examples/evaluation/Getting_Started_with_OpenAI_Evals.ipynb

Creating Eval dataset

---

examples/evaluation/Getting_Started_with_OpenAI_Evals.ipynb

Eval dataset creation

---

examples/evaluation/Getting_Started_with_OpenAI_Evals.ipynb

Eval Registry

---

articles/related_resources.md

Includes a brief description for Vellum in the Related Resources page.
Inform developers of a platform that helps them build increasingly complex applications with OpenAI models.
---

Add Vellum to Related Resources Page

---

articles/related_resources.md

Add a line for Baserun in the Related Resources page
---

Add Baserun to Related Resources

---

examples/Clustering.ipynb

The current comment is misleading as it says text-davinci-003; however, the code uses gpt-4. Text-davinci-003 is deprecated.
This PR updates the comment to correctly reflect the use of GPT-4 in the code, replacing the outdated reference to text-davinci-003. The goal is to provide accurate documentation and eliminate any confusion regarding the model version used in the cookbook.
The changes are necessary to maintain the accuracy and relevance of the documentation. By updating the comment to match the code, we ensure that users have a clear understanding of the model being used, which is crucial for replicating results and troubleshooting. This improvement enhances the overall usability and reliability of the cookbook.
--- …

Update deprecated comment to reflect use of gpt-4 in Clustering.ipynb

---

examples/Using_embeddings.ipynb

updating for latest embedding models

---

examples/How_to_stream_completions.ipynb

Clean up one unnecessarily complicated line that may have been just copy-pasted from the line above it in the `How_to_stream_completions.ipynb` notebook.
This makes the code in this important tutorial more readable and less confusing.
---

Clean up streaming code

---

articles/what_is_new_with_dalle_3.mdx
examples/vector_databases/README.md

This PR fixes a broken link and converts another link to `https` protocol.

Fix broken link

---

examples/gpt4o/introduction_to_gpt4o.ipynb

Markdown wasn't rendered properly; updated code to print outputs instead

Change from display(Markdown) to print()

---

examples/evaluation/Getting_Started_with_OpenAI_Evals.ipynb

Minor updates for clarity on path of the eval YAML file and the eval dataset. 
Added a few sentences so developers can more easily follow along the execution of evals in the cookbook. 
---

Msingh openai evalcookbook update

---

authors.yaml
examples/Developing_hallucination_guardrails.ipynb

Header + Profile Pic changes

---

examples/vector_databases/cassandra_astradb/Philosophical_Quotes_CQL.ipynb

partioning -> partitioning
---

docs: update Philosophical_Quotes_CQL.ipynb

---

examples/chatgpt/sharepoint_azure_function/Using_Azure_Functions_and_Microsoft_Graph_to_Query_SharePoint.md
examples/chatgpt/sharepoint_azure_function/solution_one_file_retrieval.js

fixed code repository for solution one in Sharepoint solution

---

examples/How_to_count_tokens_with_tiktoken.ipynb
examples/How_to_format_inputs_to_ChatGPT_models.ipynb

Remove references to file that no longer exists. Resolves #1163

Remove chatml references

---

examples/api_request_parallel_processor.py

This PR updates the example of parallel requests to API to allow cool down for AzureOpenAI API.
The current code supports both OpenAI and AzureOpenAI APIs, but the rate limit error will not be correctly detected when using AzureOpenAI due to the difference in error messages. An example of AzureOpenAI's rate limit error is:
```text
{'code': '429', 'message': 'Requests to the Embeddings_Create Operation under Azure OpenAI API version 2023-12-01-preview have exceeded call rate limit of your current OpenAI S0 pricing tier. Please retry after 8 seconds. Please go here: https://aka.ms/oai/quotaincrease if you would like to further increase the default rate limit.'}
```
And this leads to the cool down code never activated.
---
When contributing new content, read through our [contribution …

Update rate limit error detection criteria for Azure OpenAI API

---

examples/How_to_call_functions_with_chat_models.ipynb

Minor bug fix, changed: 
tool_query_string = eval(tool_calls[0].function.arguments)['query']
to
tool_query_string = json.loads(tool_calls[0].function.arguments)['query']
Minor bug fix 
---

Minor bug fix

---

examples/chatgpt/gpt_actions_library/gpt_action_bigquery.ipynb
examples/chatgpt/sharepoint_azure_function/Using_Azure_Functions_and_Microsoft_Graph_to_Query_SharePoint.md

Fixing broken links of two cookbooks in ChatGPT section (Azure Function & Bigquery).
Redirecting to correct documentation.
---
N/A

fixing broken links azure function and bigquery cookbook

---

authors.yaml
registry.yaml

Eszuhany openai patch 2

---

examples/vector_databases/qdrant/Using_Qdrant_for_embeddings_search.ipynb

Fix for unmatched '[' error.
Execution failed when running locally
---

fix syntax

---

examples/chatgpt/gpt_actions_library/gpt_action_salesforce.ipynb

Changing cell type of instructions to code for website display correctly

[GPT Actions Library] Salesforce cookbook - fix instructions

---

examples/chatgpt/gpt_actions_library/gpt_action_snowflake_direct.ipynb

Improvements to the Snowflake Direct Connect recipe. Now explains network policies and uses a corrected snowflake api url instead of the legacy url scheme. Minor wording updates for clarity.
The improved clarity here should reduce the trial-and-error required to set up this integration.
---

Improvements to GPT Actions library - Snowflake Direct

---

examples/Chat_finetuning_data_prep.ipynb

fix typo in python code example

---

examples/chatgpt/gpt_actions_library/gpt_action_snowflake_direct.ipynb

Fixing typos found by human and ChatGPT
Clear understanding

Fixing typos

---

registry.yaml

Adding chatgpt additional tags to actions library cookbooks

Adding Actions Library tags to registry.yaml

---

registry.yaml

fix registry

---

registry.yaml

Some tags aren't supported, so let's remove them

Fix registry tags

---

examples/Orchestrating_agents.ipynb

fix: typo in Orchestrating_agents.ipynb

---

registry.yaml

Add GH to registry
For GitHub GPT

Add GH to registry

---

examples/Orchestrating_agents.ipynb

Typo "conretely" in Orchestrating_agents.ipynb

---

examples/o1/Using_reasoning_for_data_validation.ipynb

fix: small typo in `Update Using_reasoning_for_data_validation.ipynb`

---

examples/Custom-LLM-as-a-Judge.ipynb

Discussed offline with @shyamal-anadkat

Update CoT ordering in Custom LLM as a Judge cookbook

---

examples/chatgpt/gpt_actions_library/gpt_action_retool_workflow.md

Switch static assets to Arcade embeds now that i've updated the cookbook site to support this.

Switch to Arcade embed.

---

authors.yaml
examples/How_to_call_functions_for_knowledge_retrieval.ipynb
registry.yaml

Replace a deprecated model (i.e., gpt-3.5-turbo-0613) with a stable version (gpt-3.5-turbo) on an existing notebook (https://cookbook.openai.com/examples/how_to_call_functions_for_knowledge_retrieval)
This change ensures the notebook runs smoothly without errors. Model outputs are also updated because of the change of the model and their non-determinism
---
~- [ ] Relevance: This content is related to building with OpenAI technologies and is useful to others.~
~- [ ] Uniqueness: I have searched for related examples in the OpenAI Cookbook, and verified that my content offers new insights or unique …

Replace an old model with a stable version on "How to use functions with a knowledge base"

---

examples/Question_answering_using_embeddings.ipynb
registry.yaml

Updated the code to generalize on latest GPT models (GPT-4 series) and leverage search with older and newer models. 
---

Notebook-Updates

---

examples/Embedding_Wikipedia_articles_for_search.ipynb
examples/Question_answering_using_embeddings.ipynb
registry.yaml

- Move to new client approach
- Move to latest models
- Move hosting of updated embeddings file.

Update to use new models and new client approach

---

examples/How_to_use_guardrails.ipynb

This change corrects the wording of the comment from "good request" to "bad request'.
The line initially read "Call the main function with the good request - this should get blocked". It seems more correct that it should read "Call the main function with the bad request - this should get blocked".
Thanks!
---

Fix typo in code example.

---

registry.yaml

Correct colin's author link

---

registry.yaml

Update registry date for "How to handle rate limits" to reflect recent changes.

Update registry date

---

examples/evaluation/How_to_evaluate_LLMs_for_SQL_generation.ipynb

I reorganized the section headings to make the notebook easier to understand. I additionally took some liberties reordering, merging, and in a few cases removing redundant blocks.
New table of contents (via Jupyter Lab):
Prior table of contents:
---

Clean up the organization of the SQL generation notebook

---

examples/vector_databases/redis/redisqna/redisqna.ipynb

Updated Redis as a context store with Chat Completions cookbook - updated the out of date usage of the OpenAI python SDK.
The Cookbook will not be able to run with the newest version of the python OpenAI sdk otherwise. 
---

updated redisqna cookbook to openai version >1.0.0

---

examples/Assistants_API_overview_python.ipynb

Fix invalid JSON in the `examples/Assistants_API_overview_python.ipynb` notebook.
Somehow, the JSON for this notebook was invalid. This PR can be verified using either `jq` or by opening the notebook in Jupyter.
Before this PR, the notebook failed to open, and `jq` reported an error. After this PR, the notebook opens successfully and `jq` outputs formatted JSON.
---
We will rate each of these areas on a scale from 1 to 4, and will only accept contributions that score 3 or higher on all areas. Refer to our [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md) …

Fix invalid notebook format in Assistants API overview

---

authors.yaml

adding avatar and profile pic for Bill Chen
---

added avatar and profile pic for Bill Chen

---

examples/chatgpt/gpt_actions_library/gpt_action_snowflake_direct.ipynb

Added a support scope disclaimer to help set correct customer expectations.
PwC customers reached out to us to support the integration described on the cookbook.
This support scope disclaimer will help set correct customer expectations.
---
- [] I have conducted a self-review of my content based on the [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md#rubric):
- [] Relevance: This content is related to building with OpenAI technologies and is useful to others.
We will rate each of these …

Add support scope disclaimer

---

examples/responses_api/responses_api_tool_orchestration.ipynb

"For a practical example of performing RAG on PDFs using the Responses API's file search feature, refer to [this](https://cookbook.openai.com/examples/file_search_responses) notebook.\n",
"This example showcases the flexibility of the Responses API, illustrating that beyond the internal `file_search` tool—which connects to an internal vector store—there is also the capability to easily connect to external vector databases. This allows for the implementation of a RAG approach in conjunction with hosted tooling, providing a versatile solution for various retrieval and generation tasks."
Updated text content on …

updated text content within responses API

---

examples/Orchestrating_agents.ipynb

Simple typo
Fix typo. "satesfied" vs "satisfied".
---

Update Orchestrating_agents.ipynb: typo

---

authors.yaml
registry.yaml

Update the authors and registry

---

authors.yaml

Update julian-openai author info
Update julian-openai author info
---

julian-openai author info update

---

authors.yaml
examples/vector_databases/chroma/hyde-with-chroma-and-openai.ipynb
registry.yaml

Updates the hyde-with-chroma-and-openai cookbook to use gpt-4o, additionally fixing some small issues from library updates.
Updates the cookbook to use a newer version of gpt-4o and the openai package
---

Update model for hyde/chroma cookbook

---

registry.yaml

Updating registry to be a verified author for [this vision cookbook](https://cookbook.openai.com/examples/gpt_with_vision_for_video_understanding)
Fixes the author contribution to be the registered users
---

update user to registered author for vision 4.1 cookbook

---

examples/partners/model_selection_guide/model_selection_guide.ipynb

This pull request includes a minor correction in the `model_selection_guide.ipynb` file. The change fixes a typographical error in the title of the document.
* [`examples/partners/model_selection_guide/model_selection_guide.ipynb`](diffhunk://#diff-0dd8fc393120432fd53fb697928752ceb147d20b90ecd6a2e0e69497dcb783ccL8-R8): Corrected "Practial" to "Practical" in the title of the guide.## Summary
---
We will rate each of these areas on a scale from 1 to 4, and will only accept contributions that score 3 or higher on all areas. Refer to our [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CO …

Fixing the typo

---

registry.yaml

model selection code typo

---

README.md

Fix signup link in README

---

registry.yaml

- fix duplication in registry.yaml
- currently shows two.
---

docs: fix duplication in registry.yaml

---

authors.yaml

author typo correction

---

examples/fine-tuned_qa/reinforcement_finetuning_healthbench.ipynb

Small fix: update instruction to correct link

Small link correction to rft healthbench cookbook

---

registry.yaml

mcp powered agents registry

---

authors.yaml
examples/evaluation/use-cases/EvalsAPI_Image_Inputs.ipynb
registry.yaml

This cookbook demonstrates how to conduct sampling and model grading using image inputs in our evals API. 
I added support for image inputs for EvalsAPI. There is no cookbook to demonstrate this new functionality. Hence, this cookbook aims to share examples using image inputs with our evals product. 
---

Evals API - Image Input Cookbook

---

registry.yaml

Update tags in registry to evals cookbook

add evals tag to evals-api cookbooks

---

articles/gpt-oss/run-transformers.md

The previous command fails when copied, so split them into two so it doesnt throw an error
The previous command fails when copied, so split them into two so it doesnt throw an error
---

Split 2 combined commands

---

registry.yaml

Fix LM Studio article

---

examples/partners/eval_driven_system_design/receipt_inspection.ipynb

Evals is now supported in ZDR orgs, and this cookbook needs updating to reflect that
---

Update evals receipt cookbook to reflect eval ZDR support

---

articles/gpt-oss/fine-tune-korean.ipynb
gpt_oss_ft_kr_bilingual_clientServerArch_CORPUS_SYNCED_TOC.ipynb
registry.yaml

Add KR bilingual fine-tuning notebook

---

examples/gpt-5/gpt-5_troubleshooting_guide.ipynb
registry.yaml

Fixing wording of meta prompting vs. metaprompting

fix: fix title and adjusting wording to meta prompting section of GPT-5 Troubleshooting Cookbook
