examples/Question_answering_using_embeddings.ipynb
Many use cases require GPT-3 to respond to user questions with insightful answers. For example, a customer support chatbot may need to provide answers to common questions. The GPT models have picked up a lot of general knowledge in training, but we often need to ingest and use a large library of more specific information.
In this notebook we demonstrate a method for enabling GPT-3 able to answer questions using a library of text as a reference, by using document embeddings and retrieval.
=> Question answering using embeddings

examples/Obtain_dataset.ipynb
https://github.com/openai/openai-cookbook/commit/fd181ec78fa57e14583e27915ccdad3a084296ae updated what was previously two different get_embedding() calls w/ different models to be two identical calls. Rather than doing the same API call twice in a row, we can now just set the second variable to be equal to the first one.
=> Only get_embedding once

examples/vector_databases/Using_vector_databases_for_embeddings_search.ipynb, examples/vector_databases/qdrant/docker-compose.yaml
I added Qdrant vector database to the notebook using the same approach as you did for Pinecone and Weaviate. Due to some rate limits and other issues, I could not create the embeddings for all the documents so it may require relaunching. However, all the required logic is already in place, with a corresponding `docker-compose.yaml` file to run Qdrant in a container.
=> Add Qdrant as another example of vector database

solutions/web_crawl_Q&A/web-qa.ipynb
Remove unmatched closing brackets ")". 
The added unmatched ")" causes a syntax error. Removing it fixes the error.
=> Remove unmatched closing brackets ")"

examples/Visualizing_embeddings_in_W&B.ipynb
Hi,
I've added an example showing how to use the Weights & Biases embedding projector with OpenAI embeddings. Let me know if there's anything I can change to help it get merged. 
Here's an example that was created by it: [http://wandb.me/openai_embeddings](http://wandb.me/openai_embeddings)
You can dynamically change what dimensionality reduction algorithm is used, along with choosing which of your logged data is shown with color & hover.
=> Add W&B embedding projector example

examples/vector_databases/Using_vector_databases_for_embeddings_search.ipynb, examples/vector_databases/redis/README.md, examples/vector_databases/redis/docker-compose.yml, examples/vector_databases/redis/getting-started-with-redis-and-openai.ipynb, examples/vector_databases/redis/nbutils.py, examples/vector_databases/redis/redis.conf
This PR adds in Redis examples for the vector database section. Redis is now in the main "into to vector dbs" notebook as well as a new folder dedicated to redis-specific examples. 
The Redis example notebook details
- Setting up an index
- Loading documents
- simple querying
- hybrid querying
- index types (FLAT vs HNSW)
A couple items are in progress that can be included in this PR or subsequent PRs
- Q/A example
- Async example
- JSON storage example
=> Add Redis example notebooks and READMEs

examples/vector_databases/qdrant/QA_with_Langchain_Qdrant_and_OpenAI.ipynb, examples/vector_databases/qdrant/docker-compose.yaml
This PR adds two additional notebooks on how to use Qdrant as a vector database with OpenAI embeddings. The changes include the following:
- "Getting started with Qdrant and OpenAI" notebook with end-to-end processing of search using the embeddings
- "QA with Langchain Qdrant and OpenAI" notebook with an example of using Qdrant and OpenAI in a Langchain application to create a Question-Answering system. The library is becoming popular, and due to many questions around that, I want to show that case.
@colin-openai, Could you please review the notebooks?
=> Add Qdrant notebooks

apps/web-crawl-q-and-a/web-qa.py
I have added handling for the last chunk in the split_into_sentences function. Previously, the function did not account for the last chunk, which could lead to incomplete sentences in the output.
To solve this, I added a conditional statement to check if the last chunk is non-empty. If it is, I append it to the list of chunks with a period to ensure the last sentence is complete.
This change improves the accuracy of the split_into_sentences function and ensures that all sentences in the input text are properly segmented. Please review and let me know if you have any feedback or concerns.
=> Add handling for last chunk in split_into_sentences function

examples/api_request_parallel_processor.py
When counting token consumption for multiple prompts, completion tokens should be multiplied by the length of the prompt list.
=> fix prompt list counter

techniques_to_improve_reliability.md
Propose the following change: 
- "For example, if you were you can try more..." -> "For example, you can try more..."
I think that "wanted" instead of "were" was originally intended. However, I think "if you wanted" is unnecessary here.
=> Fix typo in `techniques_to_improve_reliability.md`

examples/api_request_parallel_processor.py
1. Use regex to match the API endpoint component.
2. Add support for the chat/completions endpoint.
3. Replace eval with `json.loads` for more robustness and safety.
=> Add chat endpoint support

examples/How_to_count_tokens_with_tiktoken.ipynb
Before my change:
After my change:
I implemented and tested a lib that produces same tokenization: https://github.com/dmitry-brazhenko/SharpToken
=> Added sharptoken as example 

techniques_to_improve_reliability.md
=> [Fix] typo in techniques_to_improve_reliability.md

examples/vector_databases/Using_vector_databases_for_embeddings_search.ipynb, examples/vector_databases/milvus/Filtered_search_with_Milvus_and_OpenAI.ipynb, examples/vector_databases/milvus/Getting_started_with_Milvus_and_OpenAI.ipynb, examples/vector_databases/zilliz/Filtered_search_with_Zilliz_and_OpenAI.ipynb, examples/vector_databases/zilliz/Getting_started_with_Zilliz_and_OpenAI.ipynb
Included the Zilliz vector database, Milvus bugfixes, and more notebooks. 
Also this merge aims to clear the notebook outputs of the shared notebook. Every pull is deleting other peoples outputs and including their own. I believe the best route is to just not have outputs in the notebook instead of everyone overwriting each others work.
=> Zilliz integration and Milvus bugfixes

apps/web-crawl-q-and-a/web-qa.py
Updated the get_domain_hyperlinks function to include handling of tel: links in addition to mailto: links, to exclude them from the clean links list.
=> Added or link.startswith("tel:") in the condition to exclude tel: links from clean links.

examples/Embedding_Wikipedia_articles_for_search.ipynb
This resolves the mismatch between the values in markdown cell and code cell which may confuse readers.
(BTW, between this and the downstream Q&A example, I believe this notebook is a far more valuable example.)
=> Update the section token count from 1,000 to 1,600

examples/vector_databases/analyticdb/QA_with_Langchain_AnalyticDB_and_OpenAI.ipynb
Hi there,I hope you're doing well. 
I'm excited to open this PR. This is another example of using a fully Postgres syntax compatible database 'AnalyticDB' as a datastore to build QA with Langchain and OpenAI APIs. 
As AnalyticDB can be used with Langchain directly for now. This example is a better case for user who want to use  'AnalyticDB' as a vector store.
I would really appreciate your feedback.
=> Add QA with Langchain of AnalyticDB  vector store and OpenAI example.

examples/vector_databases/hologres/Getting_started_with_Hologres_and_OpenAI.ipynb
Hello,
We would like to add Hologres as an example of vector databases (https://github.com/openai/openai-cookbook/tree/main/examples/vector_databases).
[Hologres](https://www.alibabacloud.com/help/en/hologres/latest/introduction) is a cloud-native real-time data warehouse developed by Alibaba Cloud.
The notebook briefly introduces how to create tables in Hologres, build vector indexes, and search for nearest neighbors, based on the wiki dataset.
Thank you,
Changgegng Zhao
Developer of Hologres
=> Add Hologres as a vector database with python notebook example

examples/api_request_parallel_processor.py
This change prevents `result` to be shared among all instances of `APIRequest` (see this common [gotcha](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments))
Otherwise, with the current initialisation, the `result` instance variable will gradually accumulate all errors encountered so far in the previous API Requests.
=> Fix mutable default argument in APIRequest class

examples/api_request_parallel_processor.py, examples/data/example_requests_to_parallel_process.jsonl
This metadata field allows non API parameters to be stored which could be useful for when the results need to be associated with an external source. For example, if the user has several rows of text data within a database, and they want to calculate embeddings for each row, they can now use the metadata field to save the row id so that when they parse the results back, they know which embedding corresponds to which database row.
=> Add ability to store row-level metadata

README.md
link had an extra `ipynb` appended to the end
=> fix link to search notebook

examples/vector_databases/redis/nbutils.py
Execution of getting-started-with-redis-and-openai.ipynb was failing due to broken parameters in wget call in nbutils.py
@Spartee @colin-openai
=> Fix wget download updated parameters

examples/vector_databases/Using_vector_databases_for_embeddings_search.ipynb, examples/vector_databases/zilliz/Filtered_search_with_Zilliz_and_OpenAI.ipynb, examples/vector_databases/zilliz/Getting_started_with_Zilliz_and_OpenAI.ipynb
Updating the zilliz notebooks to use a token instead of username and password. Required for it to work with current cloud.
=> update to token for zilliz

examples/vector_databases/README.md
Added the links to the missing vector databases (PolarDB and Zilliz) in the correct alphabetical order
=> Updated README.md in examples/vector_databases

examples/How_to_call_functions_with_chat_models.ipynb
- drop the need for the "formatted_messages" setup
-  bringing more in line with the simpler "Conversation" class used here ([link](https://github.com/openai/openai-cookbook/blob/950246dd0810470291aa9728c404a01aeab5a1e9/examples/How_to_call_functions_for_knowledge_retrieval.ipynb))
=> simplify pretty print

apps/web-crawl-q-and-a/web-qa.ipynb, apps/web-crawl-q-and-a/web-qa.py, examples/Classification_using_embeddings.ipynb, examples/Clustering.ipynb, examples/Clustering_for_transaction_classification.ipynb, examples/Multiclass_classification_for_transactions.ipynb, examples/Regression_using_embeddings.ipynb, examples/Semantic_text_search_using_embeddings.ipynb, examples/User_and_product_embeddings.ipynb, examples/Visualizing_embeddings_in_2D.ipynb, examples/Visualizing_embeddings_in_W&B.ipynb, examples/Visualizing_embeddings_with_Atlas.ipynb, examples/Zero-shot_classification_with_embeddings.ipynb
When looking through the examples I noticed quite a few are using `eval`, this might be potentially unsafe if someone runs it let's say on an embeddings file from someone else, could execute arbitrary python code hidden there. I am suggesting replacement with `literal_eval`, which is also used in other examples in the repo.
Also VSCode seems to insist on making some formatting changes that I haven't figured out how to stop. If this is an issue please feel free to reject.
=> replace eval with safer literal_eval

examples/How_to_count_tokens_with_tiktoken.ipynb
This adds a link to the popular [Tiktokenizer](https://tiktokenizer.vercel.app/) webapp, in the section of the "How to count tokens with tiktoken" notebook that talks about the [OpenAI Tokenizer](https://platform.openai.com/tokenizer). It retains the reference to the OpenAI Tokenizer as well.
Rationale:
- The [tiktoken FAQ](https://github.com/openai/tiktoken/issues/98) recommends Tiktokenizer as a resource, in the first line under "Usage help". Besides indicating that it is a helpful resource, this also suggests that OpenAI is already willing to direct users to it.
- Tiktokenizer supports some important encodings the OpenAI Tokenizer currently does not, such as cl100k_base. This allows users to see how text is tokenized for chat models like gpt-3.5-turbo and gpt-4, and for the embedding …
=> Add Tiktokenizer link in "How to count tokens"

examples/Chat_finetuning_data_prep.ipynb
The following fixes checking .jsonl finetuning files that contain UTF-8 characters, specifically the error "UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 737: character maps to <undefined".
I also removed an unused "os" import.
=> Fix UTF-8 encoding in Chat_finetuning_data_prep.ipynb

README.md
the previous link pointed to a blog with multiple articles. this is a clearer link to point to
=> update semantic kernel link

examples/vector_databases/README.md
As a complement to #655 , this adds the "Cassandra/Astra DB" entry to the `vector_databases/README.md` listing of vector-DB providers.
=> Add Cassandra/Astra DB to the vector databases overall README

examples/vector_databases/cassandra_astradb/Philosophical_Quotes_cassIO.ipynb
This PR slightly modifies one of the Cassandra/Astra DB notebooks, the one which shows usage of the CassIO library, to show how to perform concurrent insertions. This change reflects the same demonstration being already present in the "pure-CQL" counterpart notebook of the same example workload.
(incidentally, the execution count of the last cells is also corrected, which was the previous+2 instead of +1).
Thank you for a review!
=> Partitioned case for CassIO notebook also shows concurrent inserts

examples/Search_reranking_with_cross-encoders.ipynb
I was going through this documentation and found this error. Hope my little contribution will be added.
=> Corrected spelling mistake in Search_reranking_with_cross-encoders.ipynb

apps/file-q-and-a/nextjs/.devcontainer/Dockerfile, apps/file-q-and-a/nextjs/.devcontainer/devcontainer.json, apps/file-q-and-a/nextjs/README.md
Adds a dev container for the nextjs app, to simplify testing the project directly on VS Code.
=> adds devcontainer support for file-q-and-a app

apps/web-crawl-q-and-a/web-qa.py
As of the now, the web crawler stops processing the remaining items from the link queue if any of the link is invalid. To fix the issue a new exception handling code was added to catch the exception and procced with the next item in the link queue.
=> Catch the exception and continue processing the next link

apps/file-q-and-a/nextjs/src/pages/api/process-file.ts
Assigning a value through `form.maxFileSize` directly no longer works and will result in `Type error: Property 'maxFileSize' does not exist on type 'IncomingForm'.` during compilation when doing `npm run build`.
Instead, pass options to the function/constructor as recommended by the [Formidable docs](https://github.com/node-formidable/formidable/blob/e5e25d2fd9a018c14d7f0014f0a9b8493892b68b/README.md#formidable--incomingform).
=> Fix File Q&A build error due to removed way of assigning options to the Formidable instance

examples/vector_databases/elasticsearch/elasticsearch-retrieval-augmented-generation.ipynb, examples/vector_databases/elasticsearch/elasticsearch-semantic-search.ipynb
This PR fixes Elastic Cloud sign up url in Elasticsearch Vector Database example [notebooks](https://github.com/openai/openai-cookbook/tree/main/examples/vector_databases/elasticsearch)
=> Elasticsearch: fix typo in signup url

examples/vector_databases/cassandra_astradb/Philosophical_Quotes_cassIO.ipynb
CassIO 0.1.3 shipped with a brand new zero-friction `cassio.init()` method for establishing the connection to your database (be it Astra DB or Cassandra).
This PR updates the notebook accordingly, thereby reducing a lot of the boilerplate around connecting to the DB.
(nothing else changes apart from the connection procedure and the instructions around it)
Tested both locally and on Colab.
Thank you for a review!
=> new cassIO connect experience with the newest cassio.init

examples/How_to_handle_rate_limits.ipynb
This link is currently broken on cookbook website - https://cookbook.openai.com/examples/how_to_handle_rate_limits (page end)
It's a relative link but cookbook website currently does not support `.py` files.
Updating to point to Github URL
=> Fix link to .py file

README.md
This link in the about/ page: https://openai.com/api/  is a 404. Updated the link to https://platform.openai.com/. 
Note - I could switch it to the actual API reference instead - https://platform.openai.com/docs/api-reference - happy to change the link.
Update broken README link.
=> Fix broken OpenAI API link in README

examples/Chat_finetuning_data_prep.ipynb
Correct legacy fine-tuning note
I had the current and legacy links the wrong way round in my initial commit :( 
When navigating the documentation, it is helpful to know to which fine-tuning method the instructions apply
=> Correct legacy fine-tuning note

examples/Multiclass_classification_for_transactions.ipynb
- Correct function name to prevent runtime error
- Add `pip install` to install required packages
- Add command and comment to find fine-tuned job status and model name
- To fix runtime error and enhance this example to follow
=> Fix error and enhance multiclass classification notebook

examples/api_request_parallel_processor.py
Updates api_request_parallel_processor.py to be used with Azure OpenAI service endpoints.
Changes: 
* Extract Azure endpoints also
* Use "api-key" header instead of "Authorization" for them
Using the script with Azure OpenAI deployments throws `NotImplementedError` error even though the 'completions' and 'embeddings' requests are implemented.
=> Add support for Azure deployment endpoints

examples/vector_databases/README.md
This adds Supabase (Postgres + pgvector) to the [list of vector databases](https://cookbook.openai.com/examples/vector_databases/readme).
Provides another vector database option (open source) that users can use alongside OpenAI.
Let me know if you have any thoughts or questions!
=> Adds Supabase to list of vector databases

examples/Code_search_using_embeddings.ipynb, examples/Customizing_embeddings.ipynb, examples/Multiclass_classification_for_transactions.ipynb, examples/Semantic_text_search_using_embeddings.ipynb, examples/Visualizing_embeddings_in_3D.ipynb, examples/Zero-shot_classification_with_embeddings.ipynb, examples/utils/embeddings_utils.py
This PR updates [examples/utils/embeddings_utils.py](https://github.com/openai/openai-cookbook/blob/main/examples/utils/embeddings_utils.py) and related `.ipynb` notebooks to API V1.
This PR is intended to address issue #855. 
The embeddings_utils.py file has not been [updated to API V1](https://github.com/openai/openai-python/discussions/742) which causes a number of errors:
1. Uses `a*` methods such as `acreate`
2. Doesn't use new names, e.g. `openai.Embedding.create()` -> `client.embeddings.create()`
3. Uses `engine` keyword in function calls when it should use `model`
This causes a number of the example .ipynb notebooks to fail as well.
1. Update embeddings_utils.py to API V1 per the [migration guide](https://github.com/openai/openai-python/discussions/742). 
2. Update related Python …
=> Update embeddings_utils.py and related notebooks to API V1 (issue #855)

examples/Named_Entity_Recognition_to_enrich_text.ipynb, registry.yaml
Add Named Entity Recognition (NER) notebook to enrich text using function-calling.
Hello, @simonpfish! Following up on #771 - I've incorporated the suggestions from the rubric. The PR now includes function-calling and an actionable task post-NER. Please let me know if there are any further improvements needed. Thank you!
---
When contributing new content, read through our [contribution guidelines](/CONTRIBUTING.md), and mark the following action items as completed:
We will rate each of these areas on a scale from 1 to 4, and will only accept contributions that score 3 or higher on all areas. Refer to our [contributions guidelines](/CONTRIBUTING.md) for more details.
=> add notebook for NER using Functions

examples/GPT_with_vision_for_video_understanding.ipynb
Removes an empty code block at the end of https://cookbook.openai.com/examples/gpt_with_vision_for_video_understanding
I thought that the page was cut off and kept refreshing; looks like it's just an unintentional empty code block in an otherwise complete example.
(The python patch version change was not an intentional part of the commit but it looks like there is a variety of different version numbers throughout so I figured it's not important but can change back if needed)
---
We will rate each of these areas on a scale from 1 to 4, and will only accept contributions that score 3 or higher on all …
=> remove an empty code block on video example

examples/User_and_product_embeddings.ipynb
Goal is to fix issue #858 - the solution is to point the notebook to the correct CSV file, and apply the literal_eval correctly.
The [examples/User_and_product_embeddings.ipynb](https://github.com/openai/openai-cookbook/blob/main/examples/User_and_product_embeddings.ipynb) notebook was previously not usable since it was referencing a datafile that was not being generated by the related notebook [examples/Get_embeddings_from_dataset.ipynb](https://github.com/openai/openai-cookbook/blob/main/examples/Get_embeddings_from_dataset.ipynb).
=> Fix for issue #858: User_and_product_embeddings.ipynb points to incorrect CSV

authors.yaml, examples/vector_databases/supabase/README.md, examples/vector_databases/supabase/semantic-search.mdx, registry.yaml
Adds a cookbook example to store and query OpenAI embeddings in Supabase using pgvector and Supabase's auto-generated REST API. This guide is written for JavaScript developers, but also adds callouts that explain how they can modify it for other languages.
Many Supabase customers use OpenAI embeddings in their DB (via pgvector) to perform semantic search and RAG over their data. This PR adds a guide that demonstrates exactly how to implement semantic search in Supabase using OpenAI embeddings while also following database best practices (like HNSW indexes, row level security, etc).
Supabase exposes an auto-generated REST API (based on the user's table schema), so this guide walks users through how to interact with their data via this API. There also aren't too many cookbook examples …
=> Adds semantic search example using Supabase Vector

examples/vector_databases/README.md
Adds [Tembo's](https://tembo.io/) [VectorDB Stack](https://tembo.io/docs/tembo-stacks/vector-db) to the list of vector databases.
The Tembo quick-start guide shows the user how to use the [pg_vectorize](https://github.com/tembo-io/pg_vectorize) extension, which is built on OpenAI's embeddings api and [pg vector](https://github.com/pgvector/pgvector). It is a high level API intended to be the quickest way to get started w/ OpenAI embeddings on Postgres.
=> Adds Tembo VectorDB to list of vector databases

examples/third_party/Openai_monitoring_with_wandb_weave.ipynb
This is a very minor change which updates the W&B Weave example notebook to use valid syntax.
For context, there's a variable which they want the user to assign a value to e.g. `FOO = # set a value` but this is invalid syntax and could be confusing to some users. I've edited it to be  `FOO = "" # set a value`. I discovered this while attempting to include this project in Ruff's ecosystem checks at https://github.com/astral-sh/ruff/pull/9293.
There is a minor chance that this would _increase_ confusion as the notebook will no longer fail with a syntax error if the user does not set a value. It'd be trivial to add additional code that checks the value of the variable and raises an informative error if that's a concern. I am happy to do so, but wanted to start with the smaller changer.
=> Fix syntax error in W&B weave notebook

examples/How_to_format_inputs_to_ChatGPT_models.ipynb
Fixed link to "techniques to improve reliability" by removing .md extension
Minor correction.
=> Fixed link to "techniques to improve reliability"

examples/dalle/Image_generations_edits_and_variations_with_DALL-E.ipynb
Similar to https://github.com/openai/openai-cookbook/pull/964, this notebook is failing our ecosystem checks over in Ruff due to a syntax error which is resolved by adding the missing `,`.
=> Fix syntax error in DALL-E notebook

examples/Assistants_API_overview_python.ipynb
Basic spelling update fixing typo "out" to "our":
From: Once again, let's update out Assistant either through the Dashboard or the API
To: Once again, let's update our Assistant either through the Dashboard or the API
=> fix spelling

README.md
I've seen a bunch of folks (including myself) accidentally include their API keys in PRs. I think this is because many are unaware that you can just add an `.env` file with your key. Adding that as a pointer in `README.md` - while I'm not sure if this is the place it should go, I think a pointer like this would be helpful.
Add instructions on best practices to handle API keys.
I've seen a bunch of folks (including myself) accidentally paste their API keys into PRs.
Would love your feedback if this information is helpful, and if the `README.md` file is the right place for this. Let me know what you think!
=> Instructions for OPENAI_API_KEY as env var and in IDEs

examples/How_to_stream_completions.ipynb, registry.yaml
=> Update stream chat completions API cookbook

examples/How_to_call_functions_with_chat_models.ipynb
Update function call cookbook with latest model and API specifications 
The function call cook book updated to newer model 'GPT-4o' and used the latest API specification to invoke the Chat Completions API with "role":"tool" (rather than using "role":"function")
=> Function call cookbook 

articles/related_resources.md
Remove Guardrails.ai from related_resources.md because it returns 404.
Keep the related resources up-to-date.
=> Remove Guardrails.ai from related_resources.md because it returns 404

examples/fine-tuned_qa/olympics-1-collect-data.ipynb
This PR corrects the placement of "only" and adds "the" in a Markdown cell.
These changes are necessary to adhere to proper grammatical rules, ensuring clarity and readability in the documentation. Proper grammar and clarity are essential for maintaining the quality and professionalism of the OpenAI Cookbook.
---
Rephrase for clarity by moving "only" to its proper position and adding "the". The revised sentence reads: "We chose to leave a little ambiguity and noise in the dataset, even though we were interested only in the Summer Olympics 2020." According to the rule of correct placement for limiting modifiers, "only" should be placed immediately before the word or phrase it modifies to avoid ambiguity. Adding "the" ensures proper article usage.
- The changes ensure that the documentation …
=> Correct grammatical errors in Markdown cells

authors.yaml
Website attribute must be in URI format but is not required, so removing it instead of having it empty
=> Remove empty website from authors.yaml

authors.yaml
authors.yml require a website per https://github.com/openai/openai-cookbook/blob/main/.github/authors_schema.json#L20
which I've mistakenly grasped when doing https://github.com/openai/openai-cookbook/pull/1376
Putting back website attribute and a placeholder value (being the GitHub author's page) as we require a value for it.
=> Adding github author link as website (required value)

examples/chatgpt/gpt_actions_library/gpt_action_canvaslms.ipynb
This was raised in #1370 . Maybe we don't want it to be a live link but right now it clearly seems like a valid link
=> Fix clearly broken link in Cookbook (addresses #1370)

examples/chatgpt/gpt_actions_library/gpt_action_redshift.ipynb, examples/chatgpt/gpt_actions_library/gpt_action_snowflake_direct.ipynb, examples/chatgpt/gpt_actions_library/gpt_action_sql_database.ipynb, examples/chatgpt/gpt_actions_library/gpt_middleware_aws_function.ipynb
Changing images HTML to MD in multiple cookbooks
Adding minor changes to the redshift code blocks of the cookbook so they render correctly / without extra characters
=> Patch images rendering in Redshift, AWS, Snowflake & SQL cookbook

articles/how_to_work_with_large_language_models.md
I believe this is a typo, and that this text should say "most likely", as in LLMs try to write text that has the highest probability of coming next, as opposed to "mostly likely". 
The only reference I can find to the difference between the two terms is [here](https://english.stackexchange.com/questions/412416/most-likely-or-mostly-likely#:~:text=There's%20also%20one%20more%20important,mostly%20likely%20red%22%20is%20not.), that said, it appears to be more of a theoretical consideration, and a brief skim of the internet returns very few results for "mostly likely". It's unclear what it would mean in this context for the generated text to be "mostly likely" - if it did in fact mean "mostly likely" rather than "most likely", there are likely clearer ways of articulating that given the …
=> [typo] Replace 'mostly likely' with 'most likely'

authors.yaml
hi @mwu1993 @joe-at-openai, LinkedIn images look to have expiry on it and I've changed those to your default GitHub avatar (so we avoid 404 on cookbook website)
added you both as reviewer, one would do :-)
and feel free to edit this if you want to change the picture
=> fixing linkedin images that don't render anymore (403)

authors.yaml
The name should be lowercase otherwise it doesn't compile
See summary
=> Fix bug with name config

registry.yaml
Through testing the internal generation, the naming was wrong
=> Make sure naming is right on the file

examples/o1/Using_chained_calls_for_o1_structured_outputs.ipynb, registry.yaml
Fixing a typo and also removing guides that aren't actually referenced.
See summary
=> Cleanup unused guides and typo

examples/chatgpt/gpt_actions_library/gpt_action_snowflake_direct.ipynb
Applying security policies at the network integration level is not always enough. In some cases, policies must be updated at the user level as well. 
Addressing this issue will make adoption more self-serve and help customers in cases where the GPT's error messages are not highly specific and/or lack recommended action.
=> Network policy tip

registry.yaml
Add the chatgpt-productivity tag to the registry so we have it show up as a card on our landing page.
=> Add chatgpt-productivity tag to GitHub GPT.

articles/related_resources.md
Cool resource shared by @BorisPower on real examples of deploying LLMs to production, linked to from this tweet. https://x.com/rohanpaul_ai/status/1863606579695870069?s=46
=> Add ZenML LLMops resource boris shared

examples/How_to_call_functions_with_chat_models.ipynb
Adds a missing word in a sentence.
A word is missing in [this section](https://cookbook.openai.com/examples/how_to_call_functions_with_chat_models#specifying-a-function-to-execute-sql-queries).
"Now can use these utility functions to extract a representation of the database schema." => "Now **we** can use these utility functions to extract a representation of the database schema."
=> Missing word in "How to call functions with chat models"

registry.yaml
Fix error with yaml preventing successful deploy.
=> fix registry yaml

examples/How_to_call_functions_for_knowledge_retrieval.ipynb, examples/vector_databases/qdrant/Getting_started_with_Qdrant_and_OpenAI.ipynb, examples/vector_databases/qdrant/Using_Qdrant_for_embeddings_search.ipynb
**How_to_call_functions_for_knowledge_retrieval.ipynb**
- removed hard coded query, and max_results in get_articles arxiv.Search routine along with removing sort_by routine that was interfering with retrieval accuracy.  
- Changed formatting on display (show markdown) of testing routines to improve readability
- Re-ran notebook to display accurate results
**Getting_started_with_Qdrant_and_OpenAI.ipynb**
- Updated links in prerequisites to match current platform urls.
- updated call to qdrant client.create_collection (was recreate_collection) to match current library requirements. 
- Changed model in Search Data section to be **text-embedding-ada-002** to match embeddings in file and allow results to work as intended by the notebook.
**Using_Qdrant_for_embeddings_search.ipynb**
- Updated …
=> Phundal-bugfixes across 3 scripts

examples/Orchestrating_agents.ipynb
=> Typo fixes - Update Orchestrating_agents.ipynb

authors.yaml, examples/reasoning_function_calls.ipynb, registry.yaml
This adds a cookbook demonstrating how to make function calls when using Reasoning models such as o4-mini. 
* Handling sequential function calling and reasoning steps in a loop
* Handling manual conversation orchestration vs using previous_response_id
* Inspecting reasoning summaries and token usage
=> Added example notebook for handling function calls with reasoning models

.github/scripts/check_notebooks.py, .github/workflows/validate-notebooks.yaml, .gitignore, examples/vector_databases/chroma/hyde-with-chroma-and-openai.ipynb, registry.yaml
Adds a github action to validate the format of all changed notebook files
Added to make sure only valid notebook changes are merged
1. With no `.ipynb` changes, confirmed the action passed trivially
2. Intentionally mangling a notebook (https://github.com/openai/openai-cookbook/pull/1793/commits/05f37b5d63fcdd67f214644f3e5186e61870bb39), confirmed the workflow failed:
```
Run python .github/scripts/check_notebooks.py
Validating 1 notebook(s)...
examples/vector_databases/chroma/hyde-with-chroma-and-openai.ipynb: INVALID - Notebook does not appear to be JSON: '{\n  {\n   "cell_type": "markdown",\n  ...
1 invalid notebook(s) found.
Error: Process completed with exit code 1.
```
3. With a valid notebook edit (https://github.com/openai/openai-cookbook/pull/1793/commits/c0d029708e13582ab8a11be24 …
=> Add PR action to validate notebook format

examples/Embedding_Wikipedia_articles_for_search.ipynb
I picked up this [github issue](https://github.com/openai/openai-cookbook/issues/1696) that noticed a broken link in the cookbook website. 
It would tidy up the cookbook a bit to remove/fix this broken link.
It appears that linking to a `.py` file is not supported for `cookbook.openai.com` as all the other files in the examples folder are `.ipynb`, so I thought best to remove this link. Alternatively we could specify the github url to the `api_request_parallel_processor.py` file but I thought simply removing this link would be better because the location/name of this file is likely to change in the future.
=> Removing broken link in cookbook example

examples/partners/model_selection_guide/model_selection_guide.ipynb
=> Numbering fix

examples/Whisper_prompting_guide.ipynb
Thanks for Whisper prompting guide.
https://cookbook.openai.com/examples/whisper_prompting_guide#pass-names-in-the-prompt-to-prevent-misspellings
Remove extra quotes
Fix typo
=> Fix typo: Remove extra quotes from triple quotes

examples/evaluation/use-cases/responses-evaluation.ipynb, registry.yaml
=> Evalsapi -> evals api

examples/fine-tuned_qa/reinforcement_finetuning_healthbench.ipynb, registry.yaml
- Add a disclaimer to the introduction and link to rft cookbook with graders.
- Update title in registry yaml
=> Small updates to rft healthbench

examples/agents_sdk/evaluate_agents.ipynb, registry.yaml
Fix article title to make it clear its using an external tool
=> Fix title and tags

.github/registry_schema.json, registry.yaml
Added archive status to older articles
- Removes from lists in UI
- Removes from search
- Adds notice at the top of archived article
- Still allows browsing via URL.
=> Archive older articles

examples/custom_image_embedding_search.ipynb
Fix a small typo in the custom image embedding example text - s/serach/search
Tiny cleanup of a misspelled word.
---
This should not count as new content - not adding anything to the registry nor adding to the authors list.
=> fix typo in custom image embedding example

examples/vector_databases/elasticsearch/elasticsearch-semantic-search.ipynb, registry.yaml
Upgrade completions API to responses API.
I was working through elastic search integration with OpenAI and upgrading this to Responses would be greatly beneficial to many teams.
---
=> Update elastic search cookbook to use latest API

registry.yaml
Add dropped evals tag to 'Using Evals API on Image Inputs' cookbook
=> add evals tag to cookbook

examples/evaluation/use-cases/EvalsAPI_Image_Inputs.ipynb
See title.
Logs containing images are able to be supported within EvalsAPI, both for stored completions (relatively new!) and responses, so added a section in the existing cookbook to highlight this functionality to users.
=> Update Image Evals Cookbook w/ Logs info

articles/gpt-oss/run-vllm.md
=> Update run-vllm.md: pin vllm version

articles/gpt-oss/run-vllm.md
Fixes a small typo in the code to run the gpt-oss models in vllm. 
`stop_token_ids = encoding.stop_tokens_for_assistant_action()`
should be
`stop_token_ids = encoding.stop_tokens_for_assistant_actions()` 
Confirmed here: https://github.com/openai/harmony/blob/eeece1861c65c6f60ff072fd110103abb037fb62/python/openai_harmony/__init__.py#L594
=> Small typo in run-vllm.md

articles/gpt-oss/run-vllm.md
> For local inference on consumer GPUs, [check out our Ollama guide](https://cookbook.openai.com/articles/gpt-oss/run-vllm).
In this section, the link was circular. Fix the link to point at https://cookbook.openai.com/articles/gpt-oss/run-locally-ollama
Fix link to direct readers to appropriate article.
=> Fix Ollama link in run-vllm.md

articles/gpt-oss/run-locally-ollama.md
Update run-gpt-oss-locally-ollama file to point to the correct endpoint 
---
=> Update run-gpt-oss-locally-ollama file to point to the correct endpoint

examples/gpt-5/prompt-optimization-cookbook.ipynb
=> Update prompt-optimization-cookbook.ipynb with formatting improvements

articles/openai-harmony.md
Remove unnecessary tool calling invitations from the basic system message.
---
=> openai-harmony: remove unnecessary line from basic system prompt

authors.yaml, examples/evaluation/use-cases/EvalsAPI_Audio_Inputs.ipynb, registry.yaml
Audio eval support was recently added to the evals product.  This cookbook gives customers an example of how to use the new feature.
We have existing customers wanting to try this out and this is the best way to show them how to use it.  It also aligns well with the image eval example we recently released.
---
=> Add cookbook for audio evals

examples/codex/jira-github.ipynb
Remove the title on the image so it's not shown on the table of content
https://cookbook.openai.com/examples/codex/jira-github#img-srcimagescodex_actionpng-altfull-data-flow-diagram-width500
=> Update titles in codex+jira cookbook
